<a href="https://colab.research.google.com/github/Alexandr20i/Th_coding/blob/main/Th_coding_LR1_Belov_Vinogradov_Grigorev_Semenickhin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#  Лабораторная работа №1

## 1.1 Реализовать функцию REF(), приводящую матрицу к ступенчатому виду.

In [ ]:
import numpy as np

In [ ]:
def ref(matrix):
    mat = matrix

    # Размеры матрицы
    rows, cols = mat.shape
    row_idx = 0  # Индекс текущей строки

    for col in range(cols):
        # Ищем ведущий элемент в столбце (не равный 0)
        pivot_row = None
        for r in range(row_idx, rows):
            if mat[r, col] != 0:
                pivot_row = r
                break

        # Если ведущего элемента нет, переходим к следующему столбцу
        if pivot_row is None:
            continue

        # Меняем строки местами: текущая строка <-> строка с ведущим элементом
        mat[[row_idx, pivot_row]] = mat[[pivot_row, row_idx]]

        # Применяем исключающее ИЛИ (XOR) или сложение по модулю 2 к строкам ниже
        for r in range(row_idx + 1, rows):
            if mat[r, col] != 0:
                mat[r] = (mat[r] + mat[row_idx]) % 2

        row_idx += 1

    return mat

In [ ]:
matrix = np.random.randint(0, 2, size=(3, 6))
print(matrix)

[[1 1 0 0 1 1]
 [0 1 1 0 1 0]
 [1 0 1 0 0 0]]


In [ ]:
result = ref(matrix)
print(result)

[[1 1 0 0 1 1]
 [0 1 1 0 1 0]
 [0 0 0 0 0 1]]


## 1.2 Реализовать функцию RREF(), приводящую матрицу к приведённому ступенчатому виду.

In [ ]:
def rref(matrix):

    mat = matrix

    # Размеры матрицы
    rows, cols = mat.shape
    row_idx = 0  # Индекс текущей строки

    for col in range(cols):
        # Ищем ведущий элемент в текущем столбце
        pivot_row = None
        for r in range(row_idx, rows):
            if mat[r, col] != 0:
                pivot_row = r
                break

        # Если ведущего элемента нет, продолжаем
        if pivot_row is None:
            continue

        # Меняем строки местами: текущая строка <-> строка с ведущим элементом
        mat[[row_idx, pivot_row]] = mat[[pivot_row, row_idx]]

        # Применяем исключающее ИЛИ (XOR) или сложение по модулю 2 к строкам ниже
        for r in range(rows):
            if r != row_idx and mat[r, col] != 0:
                mat[r] = (mat[r] + mat[row_idx]) % 2

        row_idx += 1

        # Останавливаем процесс, если дошли до конца строк
        if row_idx >= rows:
            break

    return mat

In [ ]:
matrix = np.random.randint(0, 2, size=(5, 6))
print(matrix)

[[0 0 0 1 0 1]
 [0 0 1 0 0 1]
 [0 1 1 0 1 1]
 [1 0 1 0 1 0]
 [0 0 0 1 0 1]]


In [ ]:
result = rref(matrix)
print(result)

[[1 0 0 0 1 1]
 [0 1 0 0 1 0]
 [0 0 1 0 0 1]
 [0 0 0 1 0 1]
 [0 0 0 0 0 0]]


## 1.3 Создать класс линейных кодов LinearCode.

### 1.3.1 На основе входной матрицы сформировать порождающую матрицу в ступенчатом виде.

In [ ]:
S = np.array([[1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
             [0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0],
             [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
             [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
             [0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0],
             [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]])
S_REF = rref(S)
print(S_REF)

[[1 0 0 0 0 1 1 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 1 0 1 0]
 [0 0 0 1 0 1 1 1 0 0 1]
 [0 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 0 0 0 1 0 1]]


### 1.3.2 Задать n равное числу столбцов и k равное числу строк полученной матрицы (без учёта полностью нулевых строк).

In [ ]:
def matrix_without_null(matrix):

    # Удаляем полностью нулевые строки
    non_zero_matrix = matrix[~np.all(matrix == 0, axis=1)]

    # k - количество строк без нулевых
    k = non_zero_matrix.shape[0]
    # n - количество столбцов
    n = non_zero_matrix.shape[1]

    return n, k

In [ ]:
G = np.random.randint(0, 2, size=(5, 6))
print(G)

[[1 0 0 1 0 1]
 [1 0 0 0 0 1]
 [0 1 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 1]]


In [ ]:
result = rref(G)
print(result)

[[1 0 0 0 0 1]
 [0 1 0 0 1 0]
 [0 0 1 0 0 1]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]


In [ ]:
n,k = matrix_without_null(result)
print(f" n = {n} \n k = {k}")

 n = 6 
 k = 4


### 1.3.3 Сформировать проверочную матрицу на основе порождающей.

In [ ]:
# Шаг 1. Сформировать матрицу 𝐆∗ в приведённом ступенчатом виде на основе порождающей.
S = np.array([[1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
             [0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0],
             [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
             [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
             [0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0],
             [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]])
matrix = rref(S)
print(matrix)

[[1 0 0 0 0 1 1 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 1 0 1 0]
 [0 0 0 1 0 1 1 1 0 0 1]
 [0 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 0 0 0 1 0 1]]


In [ ]:
# Шаг 2. Зафиксировать ведущие столбцы lead матрицы 𝐆∗.
def find_lead(mat):

    rows, cols = mat.shape
    lead_columns = []  # Список для хранения индексов ведущих столбцов

    # Проходим по каждой строке и находим первый ненулевой элемент (ведущий элемент)
    for row in range(rows):
        for col in range(cols):
            if mat[row, col] == 1:
                # Если нашли 1 (ведущий элемент), фиксируем индекс столбца
                lead_columns.append(col)
                break  # Переходим к следующей строке

    return lead_columns

lead = find_lead(matrix)
print(f"Ведущие столбцы: {lead}")

Ведущие столбцы: [0, 1, 2, 3, 4, 8]


In [ ]:
# Шаг 3. Сформировать сокращённую матрицу 𝐗, удалив ведущие столбцы матрицы 𝐆∗.
# Удаляем ведущие столбцы, оставляя только остальные
H3 = np.delete(matrix, lead, axis=1)

print("Сокращённая матрица X:")
print(H3)

Сокращённая матрица X:
[[1 1 0 0 0]
 [0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 0 1]
 [0 1 1 1 1]
 [0 0 0 0 1]]


In [ ]:
#Шаг 4. Сформировать матрицу 𝐇, поместив в строки, соответствующие позициям ведущих столбцов строки из 𝐗, а в остальные – строки единичной матрицы.
nH3,kH3 = matrix_without_null(H3)
nH4 = max(nH3,kH3)
H4 = np.eye(nH3, dtype=int)

def res(lead, H3, nH3, H4, nH4):
  n3 = 0
  n4 = 0
  resu = []
  for i in range(nH4+nH3):
    if n3 < len(lead) and i == lead[n3]:
      resu.append(H3[n3])
      n3+=1
    else:
      resu.append(H4[n4])
      n4+=1

  return np.array(resu)

result = res(lead, H3, nH3, H4, nH4)
print(result)





[[1 1 0 0 0]
 [0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 0 1]
 [0 1 1 1 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## 1.4 Сформировать все кодовые слова длины n двумя способами.

### 1.4.1 Сложить все слова из порождающего множества, оставить неповторяющиеся.


In [ ]:
# Функция для генерации уникальных кодовых слов из порождающего множества
def generate_unique_words(G):
    unique_words = set()
    rows, cols = G.shape

    for i in range(1, 2**rows):
        result = np.zeros(cols, dtype=int)
        for j in range(rows):
            if (i >> j) & 1:
                result = (result + G[j]) % 2
        unique_words.add(tuple(result))

    return np.array(list(unique_words))

In [ ]:
G = np.array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
              [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
              [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
              [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

M = np.array([[0, 1, 0, 0],  # строка 1
              [0, 0, 1, 1],  # строка 2
              [1, 1, 0, 0]]) # строка 4

H = np.array([[0, 1, 1, 1, 1, 0],
             [1, 0, 0, 0, 0, 0],
             [0, 1, 0, 0, 0, 0],
             [0, 0, 1, 0, 1, 1],
             [0, 0, 0, 1, 0, 1],
             [0, 0, 1, 0, 0, 0],
             [0, 0, 0, 0, 1, 0],
             [0, 0, 0, 1, 0, 0],
             [0, 0, 0, 0, 1, 1],
             [0, 0, 0, 0, 1, 0],
             [0, 0, 0, 0, 0, 1]])


In [ ]:
# Генерация кодовых слов
unique_words = generate_unique_words(M)
print(unique_words)


[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 1]
 [1 1 1 1]]


### 1.4.2 Взять все двоичные слова длины k, умножить каждое на G.


In [ ]:
# 1.4.2 Взять все двоичные слова длины k, умножить каждое на G.

u = np.array([1, 0, 1, 1, 0])
print('u = ', u)

v = np.dot(u,G)
v %= 2
print('v = u@G ', v)

check = np.dot(v, H)
check %= 2
print('v@H =', check)

u =  [1 0 1 1 0]
v = u@G  [1 0 1 1 1 0 1 0 0 1 0]
v@H = [0 0 0 0 0 0]


## 1.5 Вычислить кодовое расстояние получившегося кода.


In [ ]:
from itertools import combinations

# Функция для вычисления кодового расстояния
def calculate_code_distance(matrix):
    # Устанавливаем начальное большое значение для минимального веса
    min_weight = np.inf

    # Перебираем все возможные комбинации строк матрицы (от 1 до всех строк)
    for size in range(1, len(matrix) + 1):
        for subset in combinations(matrix, size):
            # Создаем результирующий вектор как сумму строк по модулю 2
            result_vector = np.zeros(len(matrix[0]), dtype=int)

            # Проход по каждой строке из подмножества
            for row in subset:
                result_vector = (result_vector + row) % 2

            # Вычисляем вес (количество ненулевых элементов) результирующего вектора
            weight = np.sum(result_vector)

            # Обновляем минимальный вес, если найден новый
            if 0 < weight < min_weight:
                min_weight = weight

    return int(min_weight)

In [ ]:
G = np.array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
              [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
              [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
              [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

In [ ]:
# Размерность матрицы G
n = G.shape[1]  # Число столбцов
k = G.shape[0]  # Число строк
print('n =', n, '\nk =', k)

# Вычисляем минимальное кодовое расстояние
d = calculate_code_distance(G)

# Вычисляем кратность обнаруживаемой ошибки
t = d - 1  # или можно оставить t = (d - 1) // 2, в зависимости от требования
print("Кодовое расстояние (d) =", d)
print("Кратность обнаруживаемой ошибки (t) =", t)

n = 11 
k = 5
Кодовое расстояние (d) = 2
Кратность обнаруживаемой ошибки (t) = 1


### 1.5.1 Внести в кодовое слово ошибку кратности не более t, умножить полученное слово на H, убедиться в обнаружении ошибки.

In [ ]:
v = np.array([1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0])
e1 = np.array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
Ve1 = (v + e1) % 2
print('v+e1', Ve1)
check = np.dot(Ve1, H)
check %= 2
print('(v+e1)@H =', check, "- error")


v+e1 [1 0 0 1 1 0 1 0 0 1 0]
(v+e1)@H = [0 1 0 0 0 0] - error


### 1.5.2 Найти для некоторого кодового слова ошибку кратности t+1 такую, что при умножении на H ошибка не может быть обнаружена.


In [ ]:
def find_error_pattern(v, H):
    # Проходим по всем парам позиций в кодовом слове
    for idx1 in range(len(v) - 1):
        for idx2 in range(idx1 + 1, len(v)):
            # Создаем вектор ошибки для двух позиций
            error_vector = np.zeros(len(v), dtype=int)
            error_vector[[idx1, idx2]] = 1  # Устанавливаем единицы на выбранных позициях

            # Вектор с ошибкой
            corrupted_codeword = (v + error_vector) % 2

            # Проверка: умножаем на проверочную матрицу
            syndrome = np.dot(corrupted_codeword, H) % 2

            # Если синдром ошибки состоит только из нулей, значит ошибка не обнаружена
            if np.all(syndrome == 0):
                return error_vector  # Возвращаем найденный вектор ошибки

    return None  # Если ни одна ошибка не прошла незамеченной

In [ ]:
e2 = find_error_pattern(v, H)
print('e2', e2)

Ve2 = (v + e2) % 2
print('v+e2', Ve2)

check = np.dot(Ve2, H)
check %= 2
print('(v+e2)@H =', check, "- no error")

e2 [0 0 0 0 0 0 1 0 0 1 0]
v+e2 [1 0 1 1 1 0 0 0 0 0 0]
(v+e2)@H = [0 0 0 0 0 0] - no error
