<a href="https://colab.research.google.com/github/Alexandr20i/Th_coding/blob/main/Th_coding_LR3_Belov_Vinogradov_Grigorev_Semenickhin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Лабораторная работа №3




In [36]:
import numpy as np
import math
import itertools as iter

In [37]:
# функция вычисления n и k на основе r
def calculate_n_k(r) :
    n = int(math.pow(2, r) - 1)
    k = n - r
    return n, k

In [38]:
# функция создания таблицы синдромов
def generate_fault_syndrome_table(H_matrix, err_count) :
    n = len(H_matrix)
    one_err = np.eye(n, dtype=int)
    fault_syndrome_table = {H_matrix[i].__str__() :  one_err[i] for i in range(n)}

    for num in range(2, err_count + 1) :
        fault_syndrome_arr = [sum(arr) % 2 for arr in np.asarray(list(iter.combinations(H_matrix, num)))]
        err_arr = [sum(arr) for arr in np.asarray(list(iter.combinations(one_err, num)))]
        for i in range(len(fault_syndrome_arr)) :
            fault_syndrome_table[fault_syndrome_arr[i].__str__()] = err_arr[i]

    return fault_syndrome_table

## 3.1 Написать функцию формирования порождающей и проверочной матриц кода Хэмминга (𝟐𝒓 − 𝟏, 𝟐𝒓 − 𝒓 − 𝟏, 𝟑) на основе параметра 𝒓, а также таблицы синдромов для всех однократных ошибок.

In [39]:
# функция создания проверочной матрицы Хемминга
def generate_hamming(n, r) :
    E = np.eye(r,dtype=int)
    H_matrix = []
    for i in range(r, 0, -1) :
        for synd in [sum(arr) for arr in np.asarray(list(iter.combinations(E, i)))] :
            H_matrix.append(synd)
    return np.asarray(H_matrix)

In [40]:
# функция создания порождающей матрицы
def generate_G_matrix_matrix(H_matrix, n, k) :
    G_matrix = np.zeros((k, n), dtype=int)
    for i in range(k) :
        G_matrix[i][i] = 1
    G_matrix[ : , k : ] = H_matrix[ : k,  : ]
    return G_matrix

## 3.2. Провести исследование кода Хэмминга для одно-, двух- и трёхкратных ошибок для 𝒓 = 𝟐, 𝟑, 𝟒.

для r = 2

In [41]:
r = 2
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H_matrix = generate_hamming(n, r)
print('H_matrix =', H_matrix, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G_matrix = generate_G_matrix_matrix(H_matrix, n, k)
print('G_matrix =', G_matrix, sep='\n', end='\n\n')
fault_syndrome_table = generate_fault_syndrome_table(H_matrix, 1)

n = 3, k = 1, d = 3

H_matrix =
[[1 1]
 [1 0]
 [0 1]]

G_matrix =
[[1 1 1]]



In [42]:
data_word = np.asarray([1])
encoded_data_word = np.matmul(data_word, G_matrix)
print(f'кодовое слово = {encoded_data_word}', end='\n\n')

fault1 = np.asarray([1, 0, 0])
fault2 = np.asarray([1, 0, 1])
fault3 = np.asarray([1, 1, 1])

err_encoded_data_word1 = encoded_data_word ^ fault1
err_encoded_data_word2 = encoded_data_word ^ fault2
err_encoded_data_word3 = encoded_data_word ^ fault3

fault_syndrome1 = np.matmul(err_encoded_data_word1, H_matrix) % 2
fault_syndrome2 = np.matmul(err_encoded_data_word2, H_matrix) % 2
fault_syndrome3 = np.matmul(err_encoded_data_word3, H_matrix) % 2
print(f'синдром 1 = {fault_syndrome1}, синдром 2 = {fault_syndrome2}, синдром 3 = {fault_syndrome3}', end='\n\n')

кодовое слово = [1 1 1]

синдром 1 = [1 1], синдром 2 = [1 0], синдром 3 = [0 0]



In [43]:
print('для однократной ошибки можем обнаружить, но не исправить : ')
if not np.array_equal(fault_syndrome1, np.zeros(r, dtype=int)) :
    print(f'ошибка в разряде :  {fault_syndrome_table[fault_syndrome1.__str__()]}', end='\n\n')
else :
  print('ошибки нет', end='\n\n')

print('для двукратной ошибки можем только обнаружить : ')
if not np.array_equal(fault_syndrome2, np.zeros(r, dtype=int)) :
    print(f'ошибка в разряде :  {fault_syndrome_table[fault_syndrome2.__str__()]}', end='\n\n')
else :
  print('ошибки нет', end='\n\n')

print('с трёхкратной ошибкой ничего сделать нельзя : ')
if not np.array_equal(fault_syndrome3, np.zeros(r, dtype=int)) :
    print(f'ошибка в разряде :  {fault_syndrome_table[fault_syndrome3.__str__()]}', end='\n\n')
else :
  print('ошибки нет', end='\n\n')

для однократной ошибки можем обнаружить, но не исправить : 
ошибка в разряде :  [1 0 0]

для двукратной ошибки можем только обнаружить : 
ошибка в разряде :  [0 1 0]

с трёхкратной ошибкой ничего сделать нельзя : 
ошибки нет



для r = 3

In [44]:
r = 3
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H_matrix = generate_hamming(n, r)
print('H_matrix =', H_matrix, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G_matrix = generate_G_matrix_matrix(H_matrix, n, k)
print('G_matrix =', G_matrix, sep='\n', end='\n\n')
fault_syndrome_table = generate_fault_syndrome_table(H_matrix, 1)

n = 7, k = 4, d = 3

H_matrix =
[[1 1 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]

G_matrix =
[[1 0 0 0 1 1 1]
 [0 1 0 0 1 1 0]
 [0 0 1 0 1 0 1]
 [0 0 0 1 0 1 1]]



In [45]:
data_word = np.asarray([1, 0, 0, 0])
encoded_data_word = np.matmul(data_word, G_matrix)
print(f'кодовое слово = {encoded_data_word}', end='\n\n')

fault1 = np.asarray([1, 0, 0, 0, 0, 0, 0])
fault2 = np.asarray([1, 1, 0, 0, 0, 0, 0])
fault3 = np.asarray([1, 1, 0, 0, 0, 0, 1])

err_encoded_data_word1 = encoded_data_word ^ fault1
err_encoded_data_word2 = encoded_data_word ^ fault2
err_encoded_data_word3 = encoded_data_word ^ fault3

fault_syndrome1 = np.matmul(err_encoded_data_word1, H_matrix) % 2
fault_syndrome2 = np.matmul(err_encoded_data_word2, H_matrix) % 2
fault_syndrome3 = np.matmul(err_encoded_data_word3, H_matrix) % 2
print(f'синдром 1 = {fault_syndrome1}, синдром 2 = {fault_syndrome2}, синдром 3 = {fault_syndrome3}', end='\n\n')

кодовое слово = [1 0 0 0 1 1 1]

синдром 1 = [1 1 1], синдром 2 = [0 0 1], синдром 3 = [0 0 0]



In [46]:
print('для однократной ошибки можем обнаружить, но не исправить : ')
if not np.array_equal(fault_syndrome1, np.zeros(r, dtype=int)) :
    print(f'ошибка в разряде :  {fault_syndrome_table[fault_syndrome1.__str__()]}', end='\n\n')
else :
  print('ошибки нет', end='\n\n')

print('для двукратной ошибки можем только обнаружить : ')
if not np.array_equal(fault_syndrome2, np.zeros(r, dtype=int)) :
    print(f'ошибка в разряде :  {fault_syndrome_table[fault_syndrome2.__str__()]}', end='\n\n')
else :
  print('ошибки нет', end='\n\n')

print('с трёхкратной ошибкой ничего сделать нельзя : ')
if not np.array_equal(fault_syndrome3, np.zeros(r, dtype=int)) :
    print(f'ошибка в разряде :  {fault_syndrome_table[fault_syndrome3.__str__()]}', end='\n\n')
else :
  print('ошибки нет', end='\n\n')

для однократной ошибки можем обнаружить, но не исправить : 
ошибка в разряде :  [1 0 0 0 0 0 0]

для двукратной ошибки можем только обнаружить : 
ошибка в разряде :  [0 0 0 0 0 0 1]

с трёхкратной ошибкой ничего сделать нельзя : 
ошибки нет



для r = 4

In [47]:
r = 4
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H_matrix = generate_hamming(n, r)
print('H_matrix =', H_matrix, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G_matrix = generate_G_matrix_matrix(H_matrix, n, k)
print('G_matrix =', G_matrix, sep='\n', end='\n\n')
fault_syndrome_table = generate_fault_syndrome_table(H_matrix, 1)

n = 15, k = 11, d = 3

H_matrix =
[[1 1 1 1]
 [1 1 1 0]
 [1 1 0 1]
 [1 0 1 1]
 [0 1 1 1]
 [1 1 0 0]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [0 1 0 1]
 [0 0 1 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

G_matrix =
[[1 0 0 0 0 0 0 0 0 0 0 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 0 0 1 1 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 1 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1]]



In [48]:
data_word = np.asarray([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
encoded_data_word = np.matmul(data_word, G_matrix)
print(f'кодовое слово = {encoded_data_word}', end='\n\n')

fault1 = np.asarray([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
fault2 = np.asarray([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
fault3 = np.asarray([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

err_encoded_data_word1 = encoded_data_word ^ fault1
err_encoded_data_word2 = encoded_data_word ^ fault2
err_encoded_data_word3 = encoded_data_word ^ fault3

fault_syndrome1 = np.matmul(err_encoded_data_word1, H_matrix) % 2
fault_syndrome2 = np.matmul(err_encoded_data_word2, H_matrix) % 2
fault_syndrome3 = np.matmul(err_encoded_data_word3, H_matrix) % 2
print(f'синдром 1 = {fault_syndrome1}, синдром 2 = {fault_syndrome2}, синдром 3 = {fault_syndrome3}', end='\n\n')

кодовое слово = [1 0 0 0 0 0 0 0 0 0 0 1 1 1 1]

синдром 1 = [1 1 1 1], синдром 2 = [0 0 0 1], синдром 3 = [0 0 0 0]



In [49]:
print('для однократной ошибки можем обнаружить, но не исправить : ')
if not np.array_equal(fault_syndrome1, np.zeros(r, dtype=int)) :
    print(f'ошибка в разряде :  {fault_syndrome_table[fault_syndrome1.__str__()]}', end='\n\n')
else :
  print('ошибки нет', end='\n\n')

print('для двукратной ошибки можем только обнаружить : ')
if not np.array_equal(fault_syndrome2, np.zeros(r, dtype=int)) :
    print(f'ошибка в разряде :  {fault_syndrome_table[fault_syndrome2.__str__()]}', end='\n\n')
else :
  print('ошибки нет', end='\n\n')

print('с трёхкратной ошибкой ничего сделать нельзя : ')
if not np.array_equal(fault_syndrome3, np.zeros(r, dtype=int)) :
    print(f'ошибка в разряде :  {fault_syndrome_table[fault_syndrome3.__str__()]}', end='\n\n')
else :
  print('ошибки нет', end='\n\n')

для однократной ошибки можем обнаружить, но не исправить : 
ошибка в разряде :  [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

для двукратной ошибки можем только обнаружить : 
ошибка в разряде :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]

с трёхкратной ошибкой ничего сделать нельзя : 
ошибки нет



## 3.3 Написать функцию формирования порождающей и проверочной матриц расширенного кода Хэмминга (𝟐𝒓, 𝟐𝒓 − 𝒓 − 𝟏, 𝟑) на основе параметра 𝒓, а также таблицы синдромов для всех однократных ошибок.

In [50]:
# функция создания проверочной расширенной матрицы Хемминга
def create_advanced_hamming(n, r) :
    H_matrix_ = np.zeros((n+1, r+1), dtype=int)
    H_matrix_[ : n, : r] = generate_hamming(n, r)
    H_matrix_[ : ,r] += 1
    return H_matrix_

In [51]:
# функция создания расширенной порождающей матрицы
def create_advanced_G_matrix(H_matrix_, n, k) :
    G_matrix_ = np.zeros((k, n+1), dtype=int)
    G_matrix_[ : ,  : n] = generate_G_matrix_matrix(H_matrix_[ : n,  : n-k], n, k)
    for i in range(k) :
        G_matrix_[i][n] = sum(G_matrix_[i]) % 2
    return G_matrix_

## 3.4. Провести исследование расширенного кода Хэмминга для одно-, двух-, трёх- и четырёхкратных ошибок для 𝒓 = 𝟐, 𝟑, 𝟒.

для r = 2

In [52]:
r = 2
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H_matrix_ = create_advanced_hamming(n, r)
print('H_matrix_ =', H_matrix_, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G_matrix_ = create_advanced_G_matrix(H_matrix_, n, k)
print('G_matrix_ =', G_matrix_, sep='\n', end='\n\n')
fault_syndrome_table = generate_fault_syndrome_table(H_matrix_, 1)

n = 3, k = 1, d = 3

H_matrix_ =
[[1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 1]]

G_matrix_ =
[[1 1 1 1]]



In [53]:
data_word = np.asarray([1])
encoded_data_word = np.matmul(data_word, G_matrix_)
print(f'кодовое слово = {encoded_data_word}', end='\n\n')

fault1 = np.asarray([1, 0, 0, 0])
fault2 = np.asarray([1, 0, 1, 0])
fault3 = np.asarray([1, 1, 0, 1])
fault4 = np.asarray([1, 1, 1, 1])

err_encoded_data_word1 = encoded_data_word ^ fault1
err_encoded_data_word2 = encoded_data_word ^ fault2
err_encoded_data_word3 = encoded_data_word ^ fault3
err_encoded_data_word4 = encoded_data_word ^ fault4

fault_syndrome1 = np.matmul(err_encoded_data_word1, H_matrix_) % 2
fault_syndrome2 = np.matmul(err_encoded_data_word2, H_matrix_) % 2
fault_syndrome3 = np.matmul(err_encoded_data_word3, H_matrix_) % 2
fault_syndrome4 = np.matmul(err_encoded_data_word4, H_matrix_) % 2
print(f'синдром 1 = {fault_syndrome1}, синдром 2 = {fault_syndrome2}, синдром 3 = {fault_syndrome3}, синдром 4 = {fault_syndrome4}')


кодовое слово = [1 1 1 1]

синдром 1 = [1 1 1], синдром 2 = [1 0 0], синдром 3 = [0 1 1], синдром 4 = [0 0 0]


In [54]:

def find_fault(fault_syndrome, r) :
    if not np.array_equal(fault_syndrome, np.zeros(r+1, dtype=int)) :
        if fault_syndrome[r] == 0 :
            print('двукратная ошибка', end='\n\n')
        else :
          print(f'ошибка в разряде :  {fault_syndrome_table[fault_syndrome.__str__()]}', end='\n\n')
    else :
        print('ошибок нет', end='\n\n')

In [55]:

print('для однократной ошибки можем обнаружить, но не исправить : ')
find_fault(fault_syndrome1, r)
print('для двукратной ошибки можем обнаружить и распознать : ')
find_fault(fault_syndrome2, r)
print('трёхкратную ошибку можем только обнаружить : ')
find_fault(fault_syndrome3, r)
print('с четырёхкратной ошибкой ничего сделать нельзя : ')
find_fault(fault_syndrome4, r)

для однократной ошибки можем обнаружить, но не исправить : 
ошибка в разряде :  [1 0 0 0]

для двукратной ошибки можем обнаружить и распознать : 
двукратная ошибка

трёхкратную ошибку можем только обнаружить : 
ошибка в разряде :  [0 0 1 0]

с четырёхкратной ошибкой ничего сделать нельзя : 
ошибок нет



для r = 3

In [56]:
r = 3
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H_matrix_ = create_advanced_hamming(n, r)
print('H_matrix_ =', H_matrix_, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G_matrix_ = create_advanced_G_matrix(H_matrix_, n, k)
print('G_matrix_ =', G_matrix_, sep='\n', end='\n\n')
fault_syndrome_table = generate_fault_syndrome_table(H_matrix_, 1)

n = 7, k = 4, d = 3

H_matrix_ =
[[1 1 1 1]
 [1 1 0 1]
 [1 0 1 1]
 [0 1 1 1]
 [1 0 0 1]
 [0 1 0 1]
 [0 0 1 1]
 [0 0 0 1]]

G_matrix_ =
[[1 0 0 0 1 1 1 0]
 [0 1 0 0 1 1 0 1]
 [0 0 1 0 1 0 1 1]
 [0 0 0 1 0 1 1 1]]



In [57]:

data_word = np.asarray([1, 0, 0, 1])
encoded_data_word = np.matmul(data_word, G_matrix_)
print(f'кодовое слово = {encoded_data_word}', end='\n\n')

fault1 = np.asarray([1, 0, 0, 0, 0, 0, 0, 0])
fault2 = np.asarray([1, 1, 0, 0, 0, 0, 0, 0])
fault3 = np.asarray([1, 1, 0, 0, 0, 0, 1, 0])
fault4 = np.asarray([1, 1, 0, 0, 0, 0, 1, 1])

err_encoded_data_word1 = encoded_data_word ^ fault1
err_encoded_data_word2 = encoded_data_word ^ fault2
err_encoded_data_word3 = encoded_data_word ^ fault3
err_encoded_data_word4 = encoded_data_word ^ fault4

fault_syndrome1 = np.matmul(err_encoded_data_word1, H_matrix_) % 2
fault_syndrome2 = np.matmul(err_encoded_data_word2, H_matrix_) % 2
fault_syndrome3 = np.matmul(err_encoded_data_word3, H_matrix_) % 2
fault_syndrome4 = np.matmul(err_encoded_data_word4, H_matrix_) % 2
print(f'синдром 1 = {fault_syndrome1}, синдром 2 = {fault_syndrome2}, синдром 3 = {fault_syndrome3}, синдром 4 = {fault_syndrome4}')

кодовое слово = [1 0 0 1 1 2 2 1]

синдром 1 = [1 1 1 1], синдром 2 = [0 0 1 0], синдром 3 = [0 0 0 1], синдром 4 = [0 0 0 0]


In [58]:
print('для однократной ошибки можем обнаружить, но не исправить : ')
find_fault(fault_syndrome1, r)
print('для двукратной ошибки можем обнаружить и распознать : ')
find_fault(fault_syndrome2, r)
print('трёхкратную ошибку можем только обнаружить : ')
find_fault(fault_syndrome3, r)
print('с четырёхкратной ошибкой ничего сделать нельзя : ')
find_fault(fault_syndrome4, r)


для однократной ошибки можем обнаружить, но не исправить : 
ошибка в разряде :  [1 0 0 0 0 0 0 0]

для двукратной ошибки можем обнаружить и распознать : 
двукратная ошибка

трёхкратную ошибку можем только обнаружить : 
ошибка в разряде :  [0 0 0 0 0 0 0 1]

с четырёхкратной ошибкой ничего сделать нельзя : 
ошибок нет



для r = 4

In [59]:
r = 4
n, k = calculate_n_k(r)
d = 3
print(f'n = {n}, k = {k}, d = {d}', end='\n\n')

# создадим проверочную матрицу Хэмминга по заданным параметрам
H_matrix_ = create_advanced_hamming(n, r)
print('H_matrix_ =', H_matrix_, sep='\n', end='\n\n')

# создадим пораждающую матрицу
G_matrix_ = create_advanced_G_matrix(H_matrix_, n, k)
print('G_matrix_ =', G_matrix_, sep='\n', end='\n\n')
fault_syndrome_table = generate_fault_syndrome_table(H_matrix_, 1)

n = 15, k = 11, d = 3

H_matrix_ =
[[1 1 1 1 1]
 [1 1 1 0 1]
 [1 1 0 1 1]
 [1 0 1 1 1]
 [0 1 1 1 1]
 [1 1 0 0 1]
 [1 0 1 0 1]
 [1 0 0 1 1]
 [0 1 1 0 1]
 [0 1 0 1 1]
 [0 0 1 1 1]
 [1 0 0 0 1]
 [0 1 0 0 1]
 [0 0 1 0 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]

G_matrix_ =
[[1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1]]



In [60]:

data_word = np.asarray([1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0])
encoded_data_word = np.matmul(data_word, G_matrix_)
print(f'кодовое слово = {encoded_data_word}', end='\n\n')

fault1 = np.asarray([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
fault2 = np.asarray([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
fault3 = np.asarray([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0])
fault4 = np.asarray([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0])

err_encoded_data_word1 = encoded_data_word ^ fault1
err_encoded_data_word2 = encoded_data_word ^ fault2
err_encoded_data_word3 = encoded_data_word ^ fault3
err_encoded_data_word4 = encoded_data_word ^ fault4

fault_syndrome1 = np.matmul(err_encoded_data_word1, H_matrix_) % 2
fault_syndrome2 = np.matmul(err_encoded_data_word2, H_matrix_) % 2
fault_syndrome3 = np.matmul(err_encoded_data_word3, H_matrix_) % 2
fault_syndrome4 = np.matmul(err_encoded_data_word4, H_matrix_) % 2
print(f'синдром 1 = {fault_syndrome1}, синдром 2 = {fault_syndrome2}, синдром 3 = {fault_syndrome3}, синдром 4 = {fault_syndrome4}')

кодовое слово = [1 0 0 1 0 1 0 0 1 0 0 3 3 3 2 3]

синдром 1 = [1 1 1 1 1], синдром 2 = [1 0 0 0 0], синдром 3 = [0 0 1 0 1], синдром 4 = [0 0 0 0 0]


In [61]:

print('для однократной ошибки можем обнаружить, но не исправить : ')
find_fault(fault_syndrome1, r)
print('для двукратной ошибки можем обнаружить и распознать : ')
find_fault(fault_syndrome2, r)
print('трёхкратную ошибку можем только обнаружить : ')
find_fault(fault_syndrome3, r)
print('с четырёхкратной ошибкой ничего сделать нельзя : ')
find_fault(fault_syndrome4, r)

для однократной ошибки можем обнаружить, но не исправить : 
ошибка в разряде :  [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

для двукратной ошибки можем обнаружить и распознать : 
двукратная ошибка

трёхкратную ошибку можем только обнаружить : 
ошибка в разряде :  [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]

с четырёхкратной ошибкой ничего сделать нельзя : 
ошибок нет

